import os

SQL_DATABASE_HOST = os.environ.get('SQL_DATABASE_HOST')
SQL_DATABASE_PORT = int(os.environ.get('SQL_DATABASE_PORT', default=3306))
SQL_DATABASE_USERNAME = os.environ.get('SQL_DATABASE_USERNAME')
SQL_DATABASE_PASSWORD = os.environ.get('SQL_DATABASE_PASSWORD')
SQL_DATABASE_NAME = os.environ.get('SQL_DATABASE_NAME')
SQL_DATABASE_URI = f'mysql+pymysql://{SQL_DATABASE_USERNAME}:{SQL_DATABASE_PASSWORD}@{SQL_DATABASE_HOST}/{SQL_DATABASE_NAME}'


MQTT_USERNAME = os.environ.get('MQTT_USERNAME')
MQTT_PASSWORD = os.environ.get('MQTT_PASSWORD')
MQTT_HOST = os.environ.get('MQTT_HOST')
MQTT_KEEPALIVE = os.environ.get('MQTT_KEEPALIVE', default=20)
MQTT_PORT = int(os.environ.get('MQTT_PORT', default=1883))
MQTT_USE_TLS = os.environ.get('MQTT_USE_TLS', default='False') in ['True', 'true', '1']

# SPARKPLUG_GROUP_ID = os.environ.get('SPARKPLUG_GROUP_ID')
SPARKPLUG_HOST_ID = os.environ.get('SPARKPLUG_HOST_ID')

# SPARKPLUG_DEATH_TOPIC = f'spBv1.0/{SPARKPLUG_GROUP_ID}/NDEATH/{SPARKPLUG_EDGE_NODE_ID}'
# SPARKPLUG_BIRTH_TOPIC = f'spBv1.0/{SPARKPLUG_GROUP_ID}/NBIRTH/{SPARKPLUG_EDGE_NODE_ID}'
# SPARKPLUG_REBIRTH_TOPIC = f'spBv1.0/{SPARKPLUG_GROUP_ID}/NCMD/{SPARKPLUG_EDGE_NODE_ID}'
# SPARKPLUG_DCMD_PREFIX = f'spBv1.0/{SPARKPLUG_GROUP_ID}/DCMD/{SPARKPLUG_EDGE_NODE_ID}/'

MQTT_CLIENT_ID = os.environ.get('MQTT_CLIENT_ID', default=f'{SPARKPLUG_HOST_ID}')